#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity.
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias mkdir="mkdir -pv"

# Use color when available.
# Better ls with exa.
alias ls="exa -aH --color=automatic --group-directories-first --git"
	alias ll="ls -l"
	alias lt="ls -TL 6"
alias grep="grep --color=auto"
alias diff="diff --color=auto"

# Dotfiles bare repository management.
alias dots="/usr/bin/git --git-dir=$HOME/.dots/ --work-tree=$HOME"

# TexLive Manager fix as described in https://wiki.archlinux.org/index.php/TeX_Live
alias tlmgr="$TEXMFDIST/scripts/texlive/tlmgr.pl --usermode"

# MyCli
alias mycli="mycli --myclirc $HOME/.config/mycli/myclirc"
