#!/bin/sh

# This is run when 'startx' or 'xinit' is executed,
# but since display managers use ~/.xprofile instead,
# .xprofile is sourced to be compatible with both.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
