#!/bin/sh

# This is run when a display manager logs in.
# Used as source for ~/.xinitrc.

numlockx on &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
nm-applet &
picom &
dunst &
udiskie &
flameshot &
# Not really needed when using startx (in general the config in ~/.profile)
# pulseaudio --start &
pasystray &

# At the end, start the WM.
exec bspwm
