#!/bin/sh

# This is run when a display manager logs in.
# Used as source for ~/.xinitrc.

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
xsetroot -cursor_name left_ptr &
numlockx on &
nm-applet &
blueman-applet &
picom &
dunst &
udiskie &
flameshot &
# Not really needed when using startx (in general the config in ~/.profile)
# pulseaudio --start &
pasystray &
setsid sxhkd &
syncthingtray --wait &

# At the end, start the WM.
exec bspwm
