#!/bin/sh

# This is run when a display manager logs in.
# Used as source for ~/.xinitrc.

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
nm-applet &
picom &
dunst &
udiskie &
flameshot &
# When not using a DM use this command.
# start-pulseaudio-x11 &
pasystray &

# At the end, start the WM.
# exec i3
