#!/bin/sh
# ~/.config/aliasrc
#

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Colorize commands when possible.
alias ls="exa -aH --color=automatic --group-directories-first --git"
