#!/bin/sh
# ~/.config/aliasrc
#

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Colorize commands when possible.
alias ls="ls -AGh --color=auto --group-directories-first"
