#!/bin/sh

# Checks if X program is already running, if not, run it.
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x statusbar > /dev/null || statusbar &

# Multihead.
if [ $(uname -n) = "arch" ]; then
	MAINMON="DP-0" 
	SECMON="HDMI-0"
	
	bspc monitor $MAINMON -d 1 2 3 4 5
	bspc monitor $SECMON -d 6 7 8 9 10

	if [ $(pgrep -f bspwm_enforce_monitor_position) < 2]; then
		bspwm_enforce_monitor_position $MAINMON '^1' &
	else
		killall bspwm_enforce_monitor_position
		bspwm_enforce_monitor_position $MAINMON '^1' &
	fi
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# General config.
bspc config border_width			5
bspc config window_gap				5
bspc config split_ratio				0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			true

# Window rules.
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
