#!/bin/sh

# Check if sxhkd is installed, I guess,
# because bspwm doesn't have keybindings by default.
pgrep -x sxhkd > /dev/null || sxhkd &

# Multihead.
if [ $(hostname) == "arch" ]; then
	bspc monitor DP-0 -d I II III IV V
	bspc monitor HDMI-0 -d VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

# General config.
bspc config border_width			5
bspc config window_gap				5
bspc config split_ratio				0.52
bspc config borderless_monocle		true
bspc config gapless_monocle			true

# Window rules.
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
